# Generated by Django 3.2 on 2021-07-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C110',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=65)),
                ('movimiento', models.BooleanField(blank=True, verbose_name='')),
                ('nivel', models.CharField(blank=True, max_length=1)),
                ('tipomoneda', models.CharField(blank=True, max_length=3)),
                ('asienautom', models.BooleanField(blank=True, verbose_name='')),
                ('ctacargo', models.CharField(blank=True, max_length=12)),
                ('ctaabono', models.CharField(blank=True, max_length=12)),
                ('validrefer', models.CharField(blank=True, max_length=1)),
                ('validproy', models.CharField(blank=True, max_length=1)),
                ('validcas', models.CharField(blank=True, max_length=1)),
                ('validdoc', models.CharField(blank=True, max_length=1)),
                ('codant', models.CharField(blank=True, max_length=15)),
                ('oficin', models.CharField(blank=True, max_length=5)),
                ('banco', models.CharField(blank=True, max_length=3)),
                ('tipocta', models.CharField(blank=True, max_length=10)),
                ('cuentbanca', models.CharField(blank=True, max_length=25)),
                ('descta1', models.CharField(blank=True, max_length=60)),
                ('descta2', models.CharField(blank=True, max_length=60)),
                ('descta3', models.CharField(blank=True, max_length=60)),
                ('descta4', models.CharField(blank=True, max_length=60)),
                ('descta5', models.CharField(blank=True, max_length=60)),
                ('descta6', models.CharField(blank=True, max_length=60)),
                ('codproy', models.CharField(blank=True, max_length=10)),
                ('feccre', models.DateTimeField(blank=True, verbose_name='')),
                ('fecmod', models.DateTimeField(blank=True, verbose_name='')),
                ('feceli', models.DateTimeField(blank=True, verbose_name='')),
                ('idusu', models.CharField(blank=True, max_length=10)),
                ('cierre', models.PositiveSmallIntegerField()),
                ('nyear', models.PositiveSmallIntegerField()),
                ('nmonth', models.PositiveSmallIntegerField()),
                ('idemp', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'C110. Plan de Cuentas',
            },
        ),
    ]
